---
# file: tasks/main.yaml

- name: "Update Package Cache (APT)"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when:
    - ansible_os_family == 'Debian'
  tags:
    - flatpak-inst-prerequisites

- name: "Install Dependencies"
  ansible.builtin.package:
    name: "{{ packages | flatten(levels=1) }}"
    state: "present"
  tags:
    - vault-inst-prerequisites
