---
# file: tasks/main.yaml

- name: "Update Package Cache (APT)"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when:
    - ansible_os_family == 'Debian'
  tags:
    - flatpak-inst-prerequisites

- name: "Install Dependencies"
  ansible.builtin.package:
    name: "{{ packages | flatten(levels=1) }}"
    state: "{{ state }}"
  tags:
    - flatpak-inst-prerequisites

- name: "Add the Flathub Flatpak Repository Remote"
  community.general.flatpak_remote:
    name: "flathub"
    flatpakrepo_url: "{{ flatpakrepo_url }}"
    method: "{{ method }}"
    state: "{{ state }}"
  tags:
    - flatpak-add-repo
