---
# file: molecule/default/molecule.yml

dependency:
  name: "galaxy"
driver:
  name: "podman"
lint: |
  yamllint .
platforms:
  - name: "${MOLECULE_DISTRO:-debian-12}"
    image: "pmikus/docker-${MOLECULE_DISTRO:-debian-12}-ansible:latest"
    pre_build_image: true
provisioner:
  name: "ansible"
  playbooks:
    converge: "${MOLECULE_PLAYBOOK:-converge.yml}"
