---
# file: molecule/default/molecule.yaml

dependency:
  name: "galaxy"
driver:
  name: "docker"
lint: |
  yamllint .
platforms:
  - name: "${DISTRO:-debian-12}"
    image: "pmikus/docker-${MOLECULE_DISTRO:-debian-12}-ansible:latest"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    privileged: true
    pre_build_image: true
provisioner:
  name: "ansible"
  playbooks:
    converge: "${MOLECULE_PLAYBOOK:-converge.yml}"
